typography_spectrum: 0.7914421237073839
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7116618698928505
  lightness: 0.3513060153927654
  saturation: 0.19069307763129473
  rhythmicContrast: 0.22089872742071748
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9880130914971232
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Leslie
  email: 'leslie@1upcoffee.com '
  url: 'http://1upcoffee.com'
name: 1up Coffee
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Leveling up once a day.
purpose: []
